### ISSUE TITLE
Box 'quetzal64' was not found

### ISSUE THREAD

**Issue by vandewilly** [fairchild/vagrant-mininet#1]
The file "quetzal64.box" described at line "config.vm.box_url", inside Vagrant file, was not found:

 config.vm.box_url = "https://github.com/downloads/fairchild/vagrant-mininet/quetzal64.box"

**Comment by jpillora** [comment]
Bump, https://github.com/downloads/fairchild/vagrant-mininet/quetzal64.box takes you to https://github.com/fairchild/vagrant-mininet/downloads where you see "File was not found."

**Comment by perldork** [comment]
Still an issue - get 404 attempting to access.

**Comment by perldork** [comment]
Went down the path of building the base box myself ( vagrant no longer supports the basebox command with the veewee plugin as of 1.5.3 ) - 

1) Install the latest Vagrant from vagrantup.com
2) Edit the file definitions/quetzal64/postinstall.sh.  Add your proxy to replace the 192.168.1.65 proxy or comment out the sed line that replaces http:// in repo URLs with the proxy prefix.
3) Run the below to install veewee and rebuild the box and add it with the updated proxy.

```
vagrant plugin install veewee

# This can take 20+ minutes even on a quad core CPU - so be patient.  You will be prompted 
# to confirm it is ok to download the base image before it starts doing the install.
veewee vbox build --force 'quetzal64'

# This only takes a few minutes. If you see any errors something's amiss - all green/OK if all goes well.
veewee vbox validate 'quetzal64'

# Export will show the path the exported box is in
veewee vbox export 'quetzal64'

# Now DELETE the image from Virtualbox ( using the Virtualbox CLI or UI )

# Ensure it isn't installed locally
vagrant box remove quetzal64

# Add the newly created box to vagrant ( path is output by export ) 
vagrant box add 'quetzal64' '/path/to/quetzal64.box' vagrant

vagrant up

# Even will all of this you may still need to hand install mininet on the VM and you
# might have an ovs-controller process to kill as well
vagrant ssh
sudo pkill -f ovs-controller
sudo apt-get install mininet
sudo  mn --test iperf
```
